return{
    ["Step1"]=function(Parent)
        local step1 = Instance.new("Frame",Parent)
        local Button = Instance.new("ImageLabel")
        local Sub_Frame = Instance.new("Frame")
        local arrow_left = Instance.new("ImageLabel")
        local Text = Instance.new("TextLabel")
        local call = Instance.new("TextButton")
        local Sub_title = Instance.new("TextLabel")
        local Title = Instance.new("TextLabel")

        step1.Name = "step1"
        step1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        step1.BackgroundTransparency = 1.000
        step1.BorderSizePixel = 0
        step1.Size = UDim2.new(1, 0, 1, 0)

        Button.Name = "Button"
        Button.Parent = step1
        Button.AnchorPoint = Vector2.new(0.5, 1)
        Button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Button.BackgroundTransparency = 1.000
        Button.Position = UDim2.new(0.5, 0, 1, -90)
        Button.Size = UDim2.new(0, 184, 0, 50)
        Button.ZIndex = 3
        Button.Image = "rbxassetid://3570695787"
        Button.ImageColor3 = Color3.fromRGB(46, 135, 255)
        Button.ScaleType = Enum.ScaleType.Slice
        Button.SliceCenter = Rect.new(100, 100, 100, 100)

        Sub_Frame.Name = "Sub_Frame"
        Sub_Frame.Parent = Button
        Sub_Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Frame.BackgroundTransparency = 1.000
        Sub_Frame.Position = UDim2.new(0, 0, 1, 0)
        Sub_Frame.Size = UDim2.new(1, 0, 0, 20)

        arrow_left.Name = "arrow_left"
        arrow_left.Parent = Sub_Frame
        arrow_left.AnchorPoint = Vector2.new(0, 0.5)
        arrow_left.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        arrow_left.BackgroundTransparency = 1.000
        arrow_left.Position = UDim2.new(0, 110, 0.5, 0)
        arrow_left.Size = UDim2.new(0, 15, 0, 15)
        arrow_left.Image = "rbxassetid://3926305904"
        arrow_left.ImageColor3 = Color3.fromRGB(47, 47, 47)
        arrow_left.ImageRectOffset = Vector2.new(364, 524)
        arrow_left.ImageRectSize = Vector2.new(36, 36)
        arrow_left.ImageTransparency = 0.250

        Text.Name = "Text"
        Text.Parent = Sub_Frame
        Text.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Text.BackgroundTransparency = 1.000
        Text.Size = UDim2.new(0.600000024, 0, 1, 0)
        Text.ZIndex = 4
        Text.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Text.Text = "Press Enter"
        Text.TextColor3 = Color3.fromRGB(47, 47, 47)
        Text.TextSize = 12.000
        Text.TextTransparency = 0.250
        Text.TextXAlignment = Enum.TextXAlignment.Right

        call.Name = "call"
        call.Parent = Button
        call.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call.BackgroundTransparency = 1.000
        call.Size = UDim2.new(1, 0, 1, 0)
        call.ZIndex = 4
        call.Font = Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call.Text = "Let's Start"
        call.TextColor3 = Color3.fromRGB(255, 255, 255)
        call.TextSize = 16.000

        Sub_title.Name = "Sub_title"
        Sub_title.Parent = step1
        Sub_title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_title.BackgroundTransparency = 1.000
        Sub_title.Position = UDim2.new(0, 140, 0, 190)
        Sub_title.Size = UDim2.new(0, 530, 0, 50)
        Sub_title.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Sub_title.Text = "Let's get to know you so you can start using the Scripts soon!"
        Sub_title.TextColor3 = Color3.fromRGB(53, 53, 53)
        Sub_title.TextSize = 21.000
        Sub_title.TextTransparency = 0.420
        Sub_title.TextWrapped = true
        Sub_title.TextXAlignment = Enum.TextXAlignment.Left
        Sub_title.TextYAlignment = Enum.TextYAlignment.Top

        Title.Name = "Title"
        Title.Parent = step1
        Title.AnchorPoint = Vector2.new(0.5, 0)
        Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title.BackgroundTransparency = 1.000
        Title.Position = UDim2.new(0.5, 0, 0, 53)
        Title.Size = UDim2.new(0, 680, 0, 130)
        Title.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title.Text = "Hey! 👋\\nWelcome to HUBWD"
        Title.TextColor3 = Color3.fromRGB(0, 0, 0)
        Title.TextSize = 50.000
        Title.TextTransparency = 0.200
        Title.TextXAlignment = Enum.TextXAlignment.Left
        Title.TextYAlignment = Enum.TextYAlignment.Bottom

        return {
            ['Title']=Title;
            ['Sub_title']=Text;
            ['Call']=call;
            ['Text']=Text;
        }
    end;
    ['Step2']=function(Parent)
        local step2 = Instance.new("Frame",Parent)
        local Options_Flags = Instance.new("Frame")
        local UIListLayout = Instance.new("UIListLayout")
        local spain = Instance.new("ImageLabel")
        local call = Instance.new("TextButton")
        local Title = Instance.new("TextLabel")
        local flag = Instance.new("ImageLabel")
        local _background = Instance.new("ImageLabel")
        local german = Instance.new("ImageLabel")
        local call_2 = Instance.new("TextButton")
        local Title_2 = Instance.new("TextLabel")
        local flag_2 = Instance.new("ImageLabel")
        local _background_2 = Instance.new("ImageLabel")
        local brazil = Instance.new("ImageLabel")
        local call_3 = Instance.new("TextButton")
        local Title_3 = Instance.new("TextLabel")
        local flag_3 = Instance.new("ImageLabel")
        local _background_3 = Instance.new("ImageLabel")
        local unitedstates = Instance.new("ImageLabel")
        local call_4 = Instance.new("TextButton")
        local Title_4 = Instance.new("TextLabel")
        local flag_4 = Instance.new("ImageLabel")
        local _background_4 = Instance.new("ImageLabel")
        local content = Instance.new("TextLabel")
        local Sub_Title = Instance.new("TextLabel")
        local Title_5 = Instance.new("TextLabel")
        local Button = Instance.new("ImageLabel")
        local Sub_Frame = Instance.new("Frame")
        local arrow_left = Instance.new("ImageLabel")
        local Text = Instance.new("TextLabel")
        local call_5 = Instance.new("TextButton")

        step2.Name = "step2"
        step2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        step2.BackgroundTransparency = 1.000
        step2.BorderSizePixel = 0
        step2.Size = UDim2.new(1, 0, 1, 0)
        step2.Visible = false

        Options_Flags.Name = "Options_Flags"
        Options_Flags.Parent = step2
        Options_Flags.AnchorPoint = Vector2.new(0.5, 0.5)
        Options_Flags.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Options_Flags.BackgroundTransparency = 1.000
        Options_Flags.BorderSizePixel = 0
        Options_Flags.Position = UDim2.new(0.5, 0, 0.5, 0)
        Options_Flags.Size = UDim2.new(1, 0, 0, 180)

        UIListLayout.Parent = Options_Flags
        UIListLayout.FillDirection = Enum.FillDirection.Horizontal
        UIListLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
        UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
        UIListLayout.VerticalAlignment = Enum.VerticalAlignment.Center
        UIListLayout.Padding = UDim.new(0, 15)

        spain.Name = "spain"
        spain.Parent = Options_Flags
        spain.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        spain.BackgroundTransparency = 1.000
        spain.Size = UDim2.new(1, -20, 1, 0)
        spain.SizeConstraint = Enum.SizeConstraint.RelativeYY
        spain.Image = "rbxassetid://3570695787"
        spain.ScaleType = Enum.ScaleType.Slice
        spain.SliceCenter = Rect.new(100, 100, 100, 100)
        spain.SliceScale = 0.120

        call.Name = "call"
        call.Parent = spain
        call.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call.BackgroundTransparency = 1.000
        call.Size = UDim2.new(1, 0, 1, 0)
        call.ZIndex = 8
        call.AutoButtonColor = false
        call.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        call.Text = ""
        call.TextColor3 = Color3.fromRGB(0, 0, 0)
        call.TextSize = 14.000

        Title.Name = "Title"
        Title.Parent = spain
        Title.AnchorPoint = Vector2.new(0.5, 0.699999988)
        Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title.BackgroundTransparency = 1.000
        Title.Position = UDim2.new(0.5, 0, 0.699999988, 0)
        Title.Size = UDim2.new(1, 0, 0, 20)
        Title.ZIndex = 3
        Title.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title.Text = "Spanish"
        Title.TextColor3 = Color3.fromRGB(43, 51, 63)
        Title.TextSize = 18.000

        flag.Name = "flag"
        flag.Parent = spain
        flag.AnchorPoint = Vector2.new(0.5, 0.200000003)
        flag.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        flag.BackgroundTransparency = 1.000
        flag.Position = UDim2.new(0.5, 0, 0.200000003, 0)
        flag.Size = UDim2.new(0, 75, 0, 75)
        flag.ZIndex = 3

        _background.Name = "_background"
        _background.Parent = spain
        _background.AnchorPoint = Vector2.new(0.5, 0.5)
        _background.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        _background.BackgroundTransparency = 1.000
        _background.Position = UDim2.new(0.5, 0, 0.5, 0)
        _background.Size = UDim2.new(1, -4, 1, -4)
        _background.ZIndex = 2
        _background.Image = "rbxassetid://3570695787"
        _background.ScaleType = Enum.ScaleType.Slice
        _background.SliceCenter = Rect.new(100, 100, 100, 100)
        _background.SliceScale = 0.100

        german.Name = "german"
        german.Parent = Options_Flags
        german.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        german.BackgroundTransparency = 1.000
        german.Size = UDim2.new(1, -20, 1, 0)
        german.SizeConstraint = Enum.SizeConstraint.RelativeYY
        german.Image = "rbxassetid://3570695787"
        german.ScaleType = Enum.ScaleType.Slice
        german.SliceCenter = Rect.new(100, 100, 100, 100)
        german.SliceScale = 0.120

        call_2.Name = "call"
        call_2.Parent = german
        call_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_2.BackgroundTransparency = 1.000
        call_2.Size = UDim2.new(1, 0, 1, 0)
        call_2.ZIndex = 8
        call_2.AutoButtonColor = false
        call_2Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        call_2.Text = ""
        call_2.TextColor3 = Color3.fromRGB(0, 0, 0)
        call_2.TextSize = 14.000

        Title_2.Name = "Title"
        Title_2.Parent = german
        Title_2.AnchorPoint = Vector2.new(0.5, 0.699999988)
        Title_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_2.BackgroundTransparency = 1.000
        Title_2.Position = UDim2.new(0.5, 0, 0.699999988, 0)
        Title_2.Size = UDim2.new(1, 0, 0, 20)
        Title_2.ZIndex = 3
        Title_2.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_2.Text = "German"
        Title_2.TextColor3 = Color3.fromRGB(43, 51, 63)
        Title_2.TextSize = 18.000

        flag_2.Name = "flag"
        flag_2.Parent = german
        flag_2.AnchorPoint = Vector2.new(0.5, 0.200000003)
        flag_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        flag_2.BackgroundTransparency = 1.000
        flag_2.Position = UDim2.new(0.5, 0, 0.200000003, 0)
        flag_2.Size = UDim2.new(0, 75, 0, 75)
        flag_2.ZIndex = 3
        flag_2.Image = "rbxasset://textures/ui/GuiImagePlaceholder.png"

        _background_2.Name = "_background"
        _background_2.Parent = german
        _background_2.AnchorPoint = Vector2.new(0.5, 0.5)
        _background_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        _background_2.BackgroundTransparency = 1.000
        _background_2.Position = UDim2.new(0.5, 0, 0.5, 0)
        _background_2.Size = UDim2.new(1, -4, 1, -4)
        _background_2.ZIndex = 2
        _background_2.Image = "rbxassetid://3570695787"
        _background_2.ScaleType = Enum.ScaleType.Slice
        _background_2.SliceCenter = Rect.new(100, 100, 100, 100)
        _background_2.SliceScale = 0.100

        brazil.Name = "brazil"
        brazil.Parent = Options_Flags
        brazil.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        brazil.BackgroundTransparency = 1.000
        brazil.Size = UDim2.new(1, -20, 1, 0)
        brazil.SizeConstraint = Enum.SizeConstraint.RelativeYY
        brazil.Image = "rbxassetid://3570695787"
        brazil.ScaleType = Enum.ScaleType.Slice
        brazil.SliceCenter = Rect.new(100, 100, 100, 100)
        brazil.SliceScale = 0.120

        call_3.Name = "call"
        call_3.Parent = brazil
        call_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_3.BackgroundTransparency = 1.000
        call_3.Size = UDim2.new(1, 0, 1, 0)
        call_3.ZIndex = 8
        call_3.AutoButtonColor = false
        call_3Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        call_3.Text = ""
        call_3.TextColor3 = Color3.fromRGB(0, 0, 0)
        call_3.TextSize = 14.000

        Title_3.Name = "Title"
        Title_3.Parent = brazil
        Title_3.AnchorPoint = Vector2.new(0.5, 0.699999988)
        Title_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_3.BackgroundTransparency = 1.000
        Title_3.Position = UDim2.new(0.5, 0, 0.699999988, 0)
        Title_3.Size = UDim2.new(1, 0, 0, 20)
        Title_3.ZIndex = 3
        Title_3.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_3.Text = "Portugueses"
        Title_3.TextColor3 = Color3.fromRGB(43, 51, 63)
        Title_3.TextSize = 18.000

        flag_3.Name = "flag"
        flag_3.Parent = brazil
        flag_3.AnchorPoint = Vector2.new(0.5, 0.200000003)
        flag_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        flag_3.BackgroundTransparency = 1.000
        flag_3.Position = UDim2.new(0.5, 0, 0.200000003, 0)
        flag_3.Size = UDim2.new(0, 75, 0, 75)
        flag_3.ZIndex = 3
        flag_3.Image = "rbxasset://textures/ui/GuiImagePlaceholder.png"

        _background_3.Name = "_background"
        _background_3.Parent = brazil
        _background_3.AnchorPoint = Vector2.new(0.5, 0.5)
        _background_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        _background_3.BackgroundTransparency = 1.000
        _background_3.Position = UDim2.new(0.5, 0, 0.5, 0)
        _background_3.Size = UDim2.new(1, -4, 1, -4)
        _background_3.ZIndex = 2
        _background_3.Image = "rbxassetid://3570695787"
        _background_3.ScaleType = Enum.ScaleType.Slice
        _background_3.SliceCenter = Rect.new(100, 100, 100, 100)
        _background_3.SliceScale = 0.100

        unitedstates.Name = "united-states"
        unitedstates.Parent = Options_Flags
        unitedstates.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        unitedstates.BackgroundTransparency = 1.000
        unitedstates.Size = UDim2.new(1, -20, 1, 0)
        unitedstates.SizeConstraint = Enum.SizeConstraint.RelativeYY
        unitedstates.Image = "rbxassetid://3570695787"
        unitedstates.ScaleType = Enum.ScaleType.Slice
        unitedstates.SliceCenter = Rect.new(100, 100, 100, 100)
        unitedstates.SliceScale = 0.120

        call_4.Name = "call"
        call_4.Parent = unitedstates
        call_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_4.BackgroundTransparency = 1.000
        call_4.Size = UDim2.new(1, 0, 1, 0)
        call_4.ZIndex = 8
        call_4.AutoButtonColor = false
        call_4Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        call_4.Text = ""
        call_4.TextColor3 = Color3.fromRGB(0, 0, 0)
        call_4.TextSize = 14.000

        Title_4.Name = "Title"
        Title_4.Parent = unitedstates
        Title_4.AnchorPoint = Vector2.new(0.5, 0.699999988)
        Title_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_4.BackgroundTransparency = 1.000
        Title_4.Position = UDim2.new(0.5, 0, 0.699999988, 0)
        Title_4.Size = UDim2.new(1, 0, 0, 20)
        Title_4.ZIndex = 3
        Title_4.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_4.Text = "English"
        Title_4.TextColor3 = Color3.fromRGB(43, 51, 63)
        Title_4.TextSize = 18.000

        flag_4.Name = "flag"
        flag_4.Parent = unitedstates
        flag_4.AnchorPoint = Vector2.new(0.5, 0.200000003)
        flag_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        flag_4.BackgroundTransparency = 1.000
        flag_4.Position = UDim2.new(0.5, 0, 0.200000003, 0)
        flag_4.Size = UDim2.new(0, 75, 0, 75)
        flag_4.ZIndex = 3
        flag_4.Image = "rbxasset://textures/ui/GuiImagePlaceholder.png"

        _background_4.Name = "_background"
        _background_4.Parent = unitedstates
        _background_4.AnchorPoint = Vector2.new(0.5, 0.5)
        _background_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        _background_4.BackgroundTransparency = 1.000
        _background_4.Position = UDim2.new(0.5, 0, 0.5, 0)
        _background_4.Size = UDim2.new(1, -4, 1, -4)
        _background_4.ZIndex = 2
        _background_4.Image = "rbxassetid://3570695787"
        _background_4.ScaleType = Enum.ScaleType.Slice
        _background_4.SliceCenter = Rect.new(100, 100, 100, 100)
        _background_4.SliceScale = 0.100

        content.Name = "content"
        content.Parent = step2
        content.AnchorPoint = Vector2.new(0.5, 0)
        content.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        content.BackgroundTransparency = 1.000
        content.Position = UDim2.new(0.5, 0, 0, 110)
        content.Size = UDim2.new(0, 500, 0, 40)
        content.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        content.Text = "Pick our suggestion or change it "
        content.TextColor3 = Color3.fromRGB(45, 57, 73)
        content.TextSize = 16.000
        content.TextTransparency = 0.380
        content.TextWrapped = true
        content.TextYAlignment = Enum.TextYAlignment.Top

        Sub_Title.Name = "Sub_Title"
        Sub_Title.Parent = step2
        Sub_Title.AnchorPoint = Vector2.new(0.5, 0)
        Sub_Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Title.BackgroundTransparency = 1.000
        Sub_Title.Position = UDim2.new(0.5, 0, 0, 65)
        Sub_Title.Size = UDim2.new(0, 500, 0, 40)
        Sub_Title.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Sub_Title.Text = "Confirm your text language"
        Sub_Title.TextColor3 = Color3.fromRGB(45, 57, 73)
        Sub_Title.TextSize = 34.000
        Sub_Title.TextWrapped = true

        Title_5.Name = "Title"
        Title_5.Parent = step2
        Title_5.AnchorPoint = Vector2.new(0.5, 0)
        Title_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_5.BackgroundTransparency = 1.000
        Title_5.Position = UDim2.new(0.5, 0, 0, 50)
        Title_5.Size = UDim2.new(0, 200, 0, 15)
        Title_5.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_5.Text = "SETUP"
        Title_5.TextColor3 = Color3.fromRGB(63, 124, 197)
        Title_5.TextSize = 14.000
        Title_5.TextWrapped = true

        Button.Name = "Button"
        Button.Parent = step2
        Button.AnchorPoint = Vector2.new(0.5, 1)
        Button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Button.BackgroundTransparency = 1.000
        Button.Position = UDim2.new(0.5, 0, 1, -90)
        Button.Size = UDim2.new(0, 184, 0, 50)
        Button.Visible = false
        Button.ZIndex = 3
        Button.Image = "rbxassetid://3570695787"
        Button.ImageColor3 = Color3.fromRGB(46, 135, 255)
        Button.ScaleType = Enum.ScaleType.Slice
        Button.SliceCenter = Rect.new(100, 100, 100, 100)

        Sub_Frame.Name = "Sub_Frame"
        Sub_Frame.Parent = Button
        Sub_Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Frame.BackgroundTransparency = 1.000
        Sub_Frame.Position = UDim2.new(0, 0, 1, 0)
        Sub_Frame.Size = UDim2.new(1, 0, 0, 20)

        arrow_left.Name = "arrow_left"
        arrow_left.Parent = Sub_Frame
        arrow_left.AnchorPoint = Vector2.new(0, 0.5)
        arrow_left.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        arrow_left.BackgroundTransparency = 1.000
        arrow_left.Position = UDim2.new(0, 110, 0.5, 0)
        arrow_left.Size = UDim2.new(0, 15, 0, 15)
        arrow_left.Image = "rbxassetid://3926305904"
        arrow_left.ImageColor3 = Color3.fromRGB(47, 47, 47)
        arrow_left.ImageRectOffset = Vector2.new(364, 524)
        arrow_left.ImageRectSize = Vector2.new(36, 36)
        arrow_left.ImageTransparency = 0.250

        Text.Name = "Text"
        Text.Parent = Sub_Frame
        Text.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Text.BackgroundTransparency = 1.000
        Text.Size = UDim2.new(0.600000024, 0, 1, 0)
        Text.ZIndex = 4
        Text.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Text.Text = "Press Enter"
        Text.TextColor3 = Color3.fromRGB(47, 47, 47)
        Text.TextSize = 12.000
        Text.TextTransparency = 0.250
        Text.TextXAlignment = Enum.TextXAlignment.Right

        call_5.Name = "call"
        call_5.Parent = Button
        call_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_5.BackgroundTransparency = 1.000
        call_5.Size = UDim2.new(1, 0, 1, 0)
        call_5.ZIndex = 4
        call_5.Font = Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call_5.Text = "Continue"
        call_5.TextColor3 = Color3.fromRGB(255, 255, 255)
        call_5.TextSize = 16.000;

        return {
            ['content']=content;
            ['Sub_Title']=Sub_Title;
            ['Spain']=Title_1;
            ['German']=Title_2;
            ['Brazil']=Title_3;
            ['English']=Title_4;
            ['Flag_spain']=flag;
            ['Flag_german']=flag_2;
            ['Flag_brazil']=flag_3;
            ['Flag_unitedstates']=flag_4;
            ['Call']=call_5;
            ['Press']=Text;
        }
    end;
    ['Step3']=function(Parent)
        local step3 = Instance.new("Frame",Parent)
        local Term = Instance.new("ImageLabel")
        local Sub_Frame = Instance.new("Frame")
        local Text1 = Instance.new("TextLabel")
        local Text2 = Instance.new("TextLabel")
        local call = Instance.new("TextButton")
        local call_2 = Instance.new("TextButton")
        local Button = Instance.new("ImageLabel")
        local Sub_Frame_2 = Instance.new("Frame")
        local arrow_left = Instance.new("ImageLabel")
        local Text = Instance.new("TextLabel")
        local call_3 = Instance.new("TextButton")
        local Dropdown = Instance.new("ImageLabel")
        local Title = Instance.new("TextLabel")
        local Icon = Instance.new("ImageLabel")
        local Theme = Instance.new("TextLabel")
        local call_4 = Instance.new("TextButton")
        local Background_Dropdown = Instance.new("ImageLabel")
        local Scrolling = Instance.new("ScrollingFrame")
        local Background = Instance.new("Frame")
        local UIListLayout = Instance.new("UIListLayout")
        local Light = Instance.new("TextButton")
        local Title_2 = Instance.new("TextLabel")
        local Dark = Instance.new("TextButton")
        local Title_3 = Instance.new("TextLabel")
        local Cool = Instance.new("TextButton")
        local Title_4 = Instance.new("TextLabel")
        local HighContrast = Instance.new("TextButton")
        local Title_5 = Instance.new("TextLabel")
        local Warm = Instance.new("TextButton")
        local Title_6 = Instance.new("TextLabel")
        local Pastel = Instance.new("TextButton")
        local Title_7 = Instance.new("TextLabel")
        local Monochromatic = Instance.new("TextButton")
        local Title_8 = Instance.new("TextLabel")
        local Location = Instance.new("ImageLabel")
        local Title_9 = Instance.new("TextLabel")
        local TextBox_ = Instance.new("TextBox")
        local Icon_2 = Instance.new("ImageLabel")
        local content = Instance.new("TextLabel")
        local Title_10 = Instance.new("TextLabel")
        local Sub_Title = Instance.new("TextLabel")
        
        step3.Name = "step3"
        step3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        step3.BackgroundTransparency = 1.000
        step3.BorderSizePixel = 0
        step3.Size = UDim2.new(1, 0, 1, 0)
        step3.Visible = false
        
        Term.Name = "Term"
        Term.Parent = step3
        Term.AnchorPoint = Vector2.new(0.5, 1)
        Term.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Term.BackgroundTransparency = 1.000
        Term.Position = UDim2.new(0.5, -130, 1, -150)
        Term.Size = UDim2.new(0, 25, 0, 25)
        Term.ZIndex = 3
        Term.Image = "rbxassetid://3570695787"
        Term.ImageColor3 = Color3.fromRGB(230, 230, 230)
        Term.ScaleType = Enum.ScaleType.Slice
        Term.SliceCenter = Rect.new(100, 100, 100, 100)
        Term.SliceScale = 0.080
        
        Sub_Frame.Name = "Sub_Frame"
        Sub_Frame.Parent = Term
        Sub_Frame.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Frame.BackgroundTransparency = 1.000
        Sub_Frame.Position = UDim2.new(1, 0, 0, 0)
        Sub_Frame.Size = UDim2.new(1, 0, 1, 0)
        
        Text1.Name = "Text1"
        Text1.Parent = Sub_Frame
        Text1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Text1.BackgroundTransparency = 1.000
        Text1.BorderSizePixel = 0
        Text1.Position = UDim2.new(0, 7, 0, 0)
        Text1.Size = UDim2.new(0, 253, 1, 0)
        Text1Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Text1.Text = "I agree with the"
        Text1.TextColor3 = Color3.fromRGB(45, 57, 73)
        Text1.TextSize = 14.000
        Text1.TextTransparency = 0.100
        Text1.TextXAlignment = Enum.TextXAlignment.Left
        
        Text2.Name = "Text2"
        Text2.Parent = Sub_Frame
        Text2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Text2.BackgroundTransparency = 1.000
        Text2.BorderSizePixel = 0
        Text2.Position = UDim2.new(0, 7, 0, 0)
        Text2.Size = UDim2.new(0, 253, 1, 0)
        Text2Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Text2.Text = "Terms and Conditions"
        Text2.TextColor3 = Color3.fromRGB(46, 135, 255)
        Text2.TextSize = 14.000
        Text2.TextTransparency = 0.100
        Text2.TextXAlignment = Enum.TextXAlignment.Right
        
        call.Name = "call"
        call.Parent = Text2
        call.AnchorPoint = Vector2.new(1, 0)
        call.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call.BackgroundTransparency = 1.000
        call.Position = UDim2.new(1, 0, 0, 0)
        call.Size = UDim2.new(0, 148, 1, 0)
        call.ZIndex = 4
        callFont.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call.Text = ""
        call.TextColor3 = Color3.fromRGB(255, 255, 255)
        call.TextSize = 16.000
        
        call_2.Name = "call"
        call_2.Parent = Term
        call_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_2.BackgroundTransparency = 1.000
        call_2.Size = UDim2.new(1, 0, 1, 0)
        call_2.ZIndex = 4
        call_2Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call_2.Text = ""
        call_2.TextColor3 = Color3.fromRGB(255, 255, 255)
        call_2.TextSize = 16.000
        
        Button.Name = "Button"
        Button.Parent = step3
        Button.AnchorPoint = Vector2.new(0.5, 1)
        Button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Button.BackgroundTransparency = 1.000
        Button.Position = UDim2.new(0.5, 0, 1, -90)
        Button.Size = UDim2.new(0, 184, 0, 50)
        Button.ZIndex = 3
        Button.Image = "rbxassetid://3570695787"
        Button.ImageColor3 = Color3.fromRGB(46, 135, 255)
        Button.ScaleType = Enum.ScaleType.Slice
        Button.SliceCenter = Rect.new(100, 100, 100, 100)
        
        Sub_Frame_2.Name = "Sub_Frame"
        Sub_Frame_2.Parent = Button
        Sub_Frame_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Frame_2.BackgroundTransparency = 1.000
        Sub_Frame_2.Position = UDim2.new(0, 0, 1, 0)
        Sub_Frame_2.Size = UDim2.new(1, 0, 0, 20)
        
        arrow_left.Name = "arrow_left"
        arrow_left.Parent = Sub_Frame_2
        arrow_left.AnchorPoint = Vector2.new(0, 0.5)
        arrow_left.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        arrow_left.BackgroundTransparency = 1.000
        arrow_left.Position = UDim2.new(0, 110, 0.5, 0)
        arrow_left.Size = UDim2.new(0, 15, 0, 15)
        arrow_left.Image = "rbxassetid://3926305904"
        arrow_left.ImageColor3 = Color3.fromRGB(47, 47, 47)
        arrow_left.ImageRectOffset = Vector2.new(364, 524)
        arrow_left.ImageRectSize = Vector2.new(36, 36)
        arrow_left.ImageTransparency = 0.250
        
        Text.Name = "Text"
        Text.Parent = Sub_Frame_2
        Text.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Text.BackgroundTransparency = 1.000
        Text.Size = UDim2.new(0.600000024, 0, 1, 0)
        Text.ZIndex = 4
        Text.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Text.Text = "Press Enter"
        Text.TextColor3 = Color3.fromRGB(47, 47, 47)
        Text.TextSize = 12.000
        Text.TextTransparency = 0.250
        Text.TextXAlignment = Enum.TextXAlignment.Right
        
        call_3.Name = "call"
        call_3.Parent = Button
        call_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_3.BackgroundTransparency = 1.000
        call_3.Size = UDim2.new(1, 0, 1, 0)
        call_3.ZIndex = 4
        call_3Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call_3.Text = "Continue"
        call_3.TextColor3 = Color3.fromRGB(255, 255, 255)
        call_3.TextSize = 16.000
        
        Dropdown.Name = "Dropdown"
        Dropdown.Parent = step3
        Dropdown.AnchorPoint = Vector2.new(0.5, 0.5)
        Dropdown.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Dropdown.BackgroundTransparency = 1.000
        Dropdown.Position = UDim2.new(0.5, 40, 0.5, 0)
        Dropdown.Size = UDim2.new(0, 300, 0, 35)
        Dropdown.Image = "rbxassetid://3570695787"
        Dropdown.ScaleType = Enum.ScaleType.Slice
        Dropdown.SliceCenter = Rect.new(100, 100, 100, 100)
        Dropdown.SliceScale = 0.120
        
        Title.Name = "Title"
        Title.Parent = Dropdown
        Title.AnchorPoint = Vector2.new(1, 0)
        Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title.BackgroundTransparency = 1.000
        Title.BorderSizePixel = 0
        Title.Size = UDim2.new(0, 130, 1, 0)
        TitleFont.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title.Text = "Theme"
        Title.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title.TextSize = 14.000
        Title.TextTransparency = 0.100
        Title.TextXAlignment = Enum.TextXAlignment.Left
        
        Icon.Name = "Icon"
        Icon.Parent = Dropdown
        Icon.AnchorPoint = Vector2.new(1, 0.5)
        Icon.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Icon.BackgroundTransparency = 1.000
        Icon.Position = UDim2.new(1, -8, 0.5, 0)
        Icon.Size = UDim2.new(0, 19, 0, 19)
        Icon.ZIndex = 4
        Icon.Image = "rbxassetid://3926305904"
        Icon.ImageColor3 = Color3.fromRGB(143, 143, 143)
        Icon.ImageRectOffset = Vector2.new(404, 284)
        Icon.ImageRectSize = Vector2.new(36, 36)
        Icon.ImageTransparency = 0.200
        
        Theme.Name = "Theme"
        Theme.Parent = Dropdown
        Theme.AnchorPoint = Vector2.new(0.5, 0.5)
        Theme.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Theme.BackgroundTransparency = 1.000
        Theme.BorderSizePixel = 0
        Theme.Position = UDim2.new(0.5, -10, 0.5, 0)
        Theme.Size = UDim2.new(1, -50, 1, 0)
        Theme.ZIndex = 3
        Theme.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Theme.Text = "Light"
        Theme.TextColor3 = Color3.fromRGB(45, 57, 73)
        Theme.TextSize = 14.000
        Theme.TextTransparency = 0.160
        Theme.TextXAlignment = Enum.TextXAlignment.Left
        
        call_4.Name = "call"
        call_4.Parent = Dropdown
        call_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        call_4.BackgroundTransparency = 1.000
        call_4.Size = UDim2.new(1, 0, 1, 0)
        call_4.ZIndex = 4
        call_4Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        call_4.Text = "Continue"
        call_4.TextColor3 = Color3.fromRGB(255, 255, 255)
        call_4.TextSize = 16.000
        
        Background_Dropdown.Name = "Background_Dropdown"
        Background_Dropdown.Parent = Dropdown
        Background_Dropdown.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Background_Dropdown.BackgroundTransparency = 1.000
        Background_Dropdown.ClipsDescendants = true
        Background_Dropdown.Position = UDim2.new(0, 0, 0.5, 0)
        Background_Dropdown.Size = UDim2.new(1, 0, 0, 0)
        Background_Dropdown.Visible = false
        Background_Dropdown.Image = "rbxassetid://3570695787"
        Background_Dropdown.ScaleType = Enum.ScaleType.Slice
        Background_Dropdown.SliceCenter = Rect.new(100, 100, 100, 100)
        Background_Dropdown.SliceScale = 0.120
        
        Scrolling.Name = "Scrolling"
        Scrolling.Parent = Background_Dropdown
        Scrolling.Active = true
        Scrolling.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Scrolling.BackgroundTransparency = 1.000
        Scrolling.BorderSizePixel = 0
        Scrolling.LayoutOrder = 1
        Scrolling.Position = UDim2.new(0, 0, 0, 20)
        Scrolling.Size = UDim2.new(1, 0, 0, 87)
        Scrolling.ZIndex = 2
        Scrolling.BottomImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
        Scrolling.CanvasSize = UDim2.new(0, 0, 0, 231)
        Scrolling.ScrollBarThickness = 6
        Scrolling.TopImage = "rbxasset://textures/ui/Scroll/scroll-middle.png"
        Scrolling.VerticalScrollBarInset = Enum.ScrollBarInset.ScrollBar
        
        Background.Name = "Background"
        Background.Parent = Scrolling
        Background.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Background.BorderSizePixel = 0
        Background.Size = UDim2.new(1, 0, 1, 0)
        Background.ZIndex = 2
        
        UIListLayout.Parent = Background
        UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
        
        Light.Name = "Light"
        Light.Parent = Background
        Light.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Light.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Light.Size = UDim2.new(1, 0, 0, 33)
        Light.ZIndex = 3
        Light.AutoButtonColor = false
        Light.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Light.Text = ""
        Light.TextColor3 = Color3.fromRGB(0, 0, 0)
        Light.TextSize = 14.000
        
        Title_2.Name = "Title"
        Title_2.Parent = Light
        Title_2.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_2.BackgroundTransparency = 1.000
        Title_2.BorderSizePixel = 0
        Title_2.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_2.Size = UDim2.new(1, -50, 1, 0)
        Title_2.ZIndex = 3
        Title_2.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_2.Text = "Light"
        Title_2.TextColor3 = Color3.fromRGB(43, 122, 204)
        Title_2.TextSize = 14.000
        Title_2.TextTransparency = 0.400
        Title_2.TextXAlignment = Enum.TextXAlignment.Left
        
        Dark.Name = "Dark"
        Dark.Parent = Background
        Dark.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Dark.BackgroundTransparency = 1.000
        Dark.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Dark.Size = UDim2.new(1, 0, 0, 33)
        Dark.ZIndex = 3
        Dark.AutoButtonColor = false
        Dark.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Dark.Text = ""
        Dark.TextColor3 = Color3.fromRGB(0, 0, 0)
        Dark.TextSize = 14.000
        
        Title_3.Name = "Title"
        Title_3.Parent = Dark
        Title_3.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_3.BackgroundTransparency = 1.000
        Title_3.BorderSizePixel = 0
        Title_3.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_3.Size = UDim2.new(1, -50, 1, 0)
        Title_3.ZIndex = 3
        Title_3.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_3.Text = "Dark"
        Title_3.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_3.TextSize = 14.000
        Title_3.TextTransparency = 0.180
        Title_3.TextXAlignment = Enum.TextXAlignment.Left
        
        Cool.Name = "Cool"
        Cool.Parent = Background
        Cool.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Cool.BackgroundTransparency = 1.000
        Cool.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Cool.Size = UDim2.new(1, 0, 0, 33)
        Cool.ZIndex = 3
        Cool.AutoButtonColor = false
        Cool.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Cool.Text = ""
        Cool.TextColor3 = Color3.fromRGB(0, 0, 0)
        Cool.TextSize = 14.000
        
        Title_4.Name = "Title"
        Title_4.Parent = Cool
        Title_4.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_4.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_4.BackgroundTransparency = 1.000
        Title_4.BorderSizePixel = 0
        Title_4.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_4.Size = UDim2.new(1, -50, 1, 0)
        Title_4.ZIndex = 3
        Title_4.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_4.Text = "Cool (Purple)"
        Title_4.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_4.TextSize = 14.000
        Title_4.TextTransparency = 0.180
        Title_4.TextXAlignment = Enum.TextXAlignment.Left
        
        HighContrast.Name = "HighContrast"
        HighContrast.Parent = Background
        HighContrast.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        HighContrast.BackgroundTransparency = 1.000
        HighContrast.BorderColor3 = Color3.fromRGB(195, 215, 229)
        HighContrast.Size = UDim2.new(1, 0, 0, 33)
        HighContrast.ZIndex = 3
        HighContrast.AutoButtonColor = false
        HighContrast.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        HighContrast.Text = ""
        HighContrast.TextColor3 = Color3.fromRGB(0, 0, 0)
        HighContrast.TextSize = 14.000
        
        Title_5.Name = "Title"
        Title_5.Parent = HighContrast
        Title_5.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_5.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_5.BackgroundTransparency = 1.000
        Title_5.BorderSizePixel = 0
        Title_5.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_5.Size = UDim2.new(1, -50, 1, 0)
        Title_5.ZIndex = 3
        Title_5.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_5.Text = "High Contrast"
        Title_5.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_5.TextSize = 14.000
        Title_5.TextTransparency = 0.180
        Title_5.TextXAlignment = Enum.TextXAlignment.Left
        
        Warm.Name = "Warm"
        Warm.Parent = Background
        Warm.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Warm.BackgroundTransparency = 1.000
        Warm.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Warm.Size = UDim2.new(1, 0, 0, 33)
        Warm.ZIndex = 3
        Warm.AutoButtonColor = false
        Warm.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Warm.Text = ""
        Warm.TextColor3 = Color3.fromRGB(0, 0, 0)
        Warm.TextSize = 14.000
        
        Title_6.Name = "Title"
        Title_6.Parent = Warm
        Title_6.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_6.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_6.BackgroundTransparency = 1.000
        Title_6.BorderSizePixel = 0
        Title_6.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_6.Size = UDim2.new(1, -50, 1, 0)
        Title_6.ZIndex = 3
        Title_6.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_6.Text = "Warm"
        Title_6.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_6.TextSize = 14.000
        Title_6.TextTransparency = 0.180
        Title_6.TextXAlignment = Enum.TextXAlignment.Left
        
        Pastel.Name = "Pastel"
        Pastel.Parent = Background
        Pastel.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Pastel.BackgroundTransparency = 1.000
        Pastel.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Pastel.Size = UDim2.new(1, 0, 0, 33)
        Pastel.ZIndex = 3
        Pastel.AutoButtonColor = false
        Pastel.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Pastel.Text = ""
        Pastel.TextColor3 = Color3.fromRGB(0, 0, 0)
        Pastel.TextSize = 14.000
        
        Title_7.Name = "Title"
        Title_7.Parent = Pastel
        Title_7.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_7.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_7.BackgroundTransparency = 1.000
        Title_7.BorderSizePixel = 0
        Title_7.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_7.Size = UDim2.new(1, -50, 1, 0)
        Title_7.ZIndex = 3
        Title_7.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_7.Text = "Pastel"
        Title_7.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_7.TextSize = 14.000
        Title_7.TextTransparency = 0.180
        Title_7.TextXAlignment = Enum.TextXAlignment.Left
        
        Monochromatic.Name = "Monochromatic"
        Monochromatic.Parent = Background
        Monochromatic.BackgroundColor3 = Color3.fromRGB(239, 247, 255)
        Monochromatic.BackgroundTransparency = 1.000
        Monochromatic.BorderColor3 = Color3.fromRGB(195, 215, 229)
        Monochromatic.Size = UDim2.new(1, 0, 0, 33)
        Monochromatic.ZIndex = 3
        Monochromatic.AutoButtonColor = false
        Monochromatic.Font = Font.new('rbxasset://fonts/families/SourceSansPro.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Monochromatic.Text = ""
        Monochromatic.TextColor3 = Color3.fromRGB(0, 0, 0)
        Monochromatic.TextSize = 14.000
        
        Title_8.Name = "Title"
        Title_8.Parent = Monochromatic
        Title_8.AnchorPoint = Vector2.new(0.5, 0.5)
        Title_8.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_8.BackgroundTransparency = 1.000
        Title_8.BorderSizePixel = 0
        Title_8.Position = UDim2.new(0.5, -10, 0.5, 0)
        Title_8.Size = UDim2.new(1, -50, 1, 0)
        Title_8.ZIndex = 3
        Title_8.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal);
        Title_8.Text = "Monochromatic"
        Title_8.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_8.TextSize = 14.000
        Title_8.TextTransparency = 0.180
        Title_8.TextXAlignment = Enum.TextXAlignment.Left
        
        Location.Name = "Location"
        Location.Parent = step3
        Location.AnchorPoint = Vector2.new(0.5, 0.400000006)
        Location.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Location.BackgroundTransparency = 1.000
        Location.Position = UDim2.new(0.5, 40, 0.400000006, 0)
        Location.Size = UDim2.new(0, 300, 0, 35)
        Location.Image = "rbxassetid://3570695787"
        Location.ScaleType = Enum.ScaleType.Slice
        Location.SliceCenter = Rect.new(100, 100, 100, 100)
        Location.SliceScale = 0.120
        
        Title_9.Name = "Title"
        Title_9.Parent = Location
        Title_9.AnchorPoint = Vector2.new(1, 0)
        Title_9.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_9.BackgroundTransparency = 1.000
        Title_9.BorderSizePixel = 0
        Title_9.Size = UDim2.new(0, 130, 1, 0)
        Title_9.Font = Font.new('rbxasset://fonts/families/GothamSSm.json',Enum.FontWeight.Bold,Enum.FontStyle.Normal); 
        Title_9.Text = "Directory folder"
        Title_9.TextColor3 = Color3.fromRGB(45, 57, 73)
        Title_9.TextSize = 14.000
        Title_9.TextTransparency = 0.100
        Title_9.TextXAlignment = Enum.TextXAlignment.Left
        
        TextBox_.Name = "TextBox_:)"
        TextBox_.Parent = Location
        TextBox_.Active = false
        TextBox_.AnchorPoint = Vector2.new(0.5, 0.5)
        TextBox_.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        TextBox_.BackgroundTransparency = 1.000
        TextBox_.Position = UDim2.new(0.5, -10, 0.5, 0)
        TextBox_.Size = UDim2.new(1, -50, 1, 0)
        TextBox_.ZIndex = 3
        TextBox_.ClearTextOnFocus = false
        TextBox_.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        TextBox_.ShowNativeInput = false
        TextBox_.Text = "..\\workspace\\HUBWD"
        TextBox_.TextColor3 = Color3.fromRGB(45, 57, 73)
        TextBox_.TextSize = 14.000
        TextBox_.TextStrokeColor3 = Color3.fromRGB(255, 255, 255)
        TextBox_.TextTransparency = 0.160
        TextBox_.TextXAlignment = Enum.TextXAlignment.Left
        
        Icon_2.Name = "Icon"
        Icon_2.Parent = Location
        Icon_2.AnchorPoint = Vector2.new(1, 0.5)
        Icon_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Icon_2.BackgroundTransparency = 1.000
        Icon_2.Position = UDim2.new(1, -8, 0.5, 0)
        Icon_2.Size = UDim2.new(0, 19, 0, 19)
        Icon_2.Image = "rbxassetid://3926305904"
        Icon_2.ImageColor3 = Color3.fromRGB(143, 143, 143)
        Icon_2.ImageRectOffset = Vector2.new(504, 4)
        Icon_2.ImageRectSize = Vector2.new(36, 36)
        Icon_2.ImageTransparency = 0.200
        
        content.Name = "content"
        content.Parent = step3
        content.AnchorPoint = Vector2.new(0.5, 0)
        content.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        content.BackgroundTransparency = 1.000
        content.Position = UDim2.new(0.5, 0, 0, 110)
        content.Size = UDim2.new(0, 500, 0, 40)
        content.Font = Font.new('rbxasset://fonts/families/Arial.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        content.Text = "Pick our suggestion or change it "
        content.TextColor3 = Color3.fromRGB(45, 57, 73)
        content.TextSize = 16.000
        content.TextTransparency = 0.380
        content.TextWrapped = true
        content.TextYAlignment = Enum.TextYAlignment.Top
        
        Title_10.Name = "Title"
        Title_10.Parent = step3
        Title_10.AnchorPoint = Vector2.new(0.5, 0)
        Title_10.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Title_10.BackgroundTransparency = 1.000
        Title_10.Position = UDim2.new(0.5, 0, 0, 50)
        Title_10.Size = UDim2.new(0, 200, 0, 15)
        Title_10.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Title_10.Text = "SETUP"
        Title_10.TextColor3 = Color3.fromRGB(63, 124, 197)
        Title_10.TextSize = 14.000
        Title_10.TextWrapped = true
        
        Sub_Title.Name = "Sub_Title"
        Sub_Title.Parent = step3
        Sub_Title.AnchorPoint = Vector2.new(0.5, 0)
        Sub_Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Sub_Title.BackgroundTransparency = 1.000
        Sub_Title.Position = UDim2.new(0.5, 0, 0, 65)
        Sub_Title.Size = UDim2.new(0, 500, 0, 40)
        Sub_Title.Font = Font.new('rbxasset://fonts/families/Roboto.json',Enum.FontWeight.Normal,Enum.FontStyle.Normal);
        Sub_Title.Text = "Choose our preference"
        Sub_Title.TextColor3 = Color3.fromRGB(45, 57, 73)
        Sub_Title.TextSize = 34.000
        Sub_Title.TextWrapped = true

        return{

        }; 
    end;
};